vich_uploader:
  db_driver: orm

  mappings:

    product_images:
      uri_prefix: /assets/images
      upload_destination: '%kernel.project_dir%/assets/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true